### ISSUE TITLE
Issue with downloading of modules file...

### ISSUE THREAD

**Issue by alexinslc** [gustafn/install-ns#3]
When I run the install-ns.sh script, around line 443 I receive an error about the file not being a valid gunzip or tar file. To resolve this, I had to manually download the module, create the module folder, comment out the if statement around lines 443 and run the script again. (Ubuntu 14.04 server)

https://github.com/gustafn/install-ns/blob/master/install-ns.sh#L443

**Comment by gustafn** [comment]
hi alex, can it be that there was a networking problem with source-forge?

I was just running

    export  version_modules=4.99.8
    wget http://heanet.dl.sourceforge.net/sourceforge/naviserver/naviserver-${version_modules}-modules.tar.gz
    tar ztvf  naviserver-4.99.8-modules.tar.gz

and everything looks fine. ... or were you configuring "version_modules" as HEAD?

**Comment by alexinslc** [comment]
It could be. I haven't had a chance to double check, I'll let you know what I find on my second time around. Thanks for responding so quickly. :smile:
